### ISSUE TITLE
Add SMA connectors

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/flatsat-platform#10]
Add SMA connectors (x4) to allow the connection of antennas to the test bed. Two connectors per channel must be used: one to connect the transceiver and one to connect the antenna.

* x1 VHF band
* x2 UHF band
* x1 S Band

Suggested part number: [SMA CONNECTOR](https://br.mouser.com/ProductDetail/LPRS/SMA-CONNECTOR?qs=j%252B1pi9TdxUYkOiITvzJM8A%3D%3D)

Example:
![sma-test-bed](https://user-images.githubusercontent.com/5316364/94977471-32beec00-04ef-11eb-9d29-1ae312fe421d.png)

**Comment by YanAzer** [comment]
@mgm8 this [one](https://www.amphenolrf.com/132134-15.html) can be used?
